// This is my first mine idea code fully generated by me
// This code is made using switch function
#include <stdio.h>
int main()
{
    int marks, age;
    printf("ENTER THE MARKS YOU OBTAINED IN YOUR CLASS 12TH EXAMINATION (IN PERCENTAGE and Rounded off to 5)\n");
    scanf("%d", &marks);
    printf("Tell me what is your age\n");
    scanf("%d", &age);
    switch (marks)
    {
    case 85:
        printf("You have got 85 percent in your class 12th examination\n");
        switch (age)
        {
        case 18:
            printf(" and your age is 18\n so you will get 80 percent off in your admission fees as scholarship\n");
            break;

        case 19:
            printf(" and your age is 19\n so you will get 70 percent off in your admission fees as scholarship\n");
            break;

        case 20:
            printf(" and your age is 20\n so you will get 60 percent off in your admission fees as scholarship\n");
            break;

        default:
            printf("As your age is either below 18 or above 20 you will not get any scholarship\n but dont be afraid your future is very bright\n");
            break;
        }
        break;
    case 90:
        printf("You have got 90 percent in your class 12th examination\n");
        switch (age)
        {
        case 18:
            printf(" and your age is 18\n so you will get 85 percent off in your admission fees as scholarship\n");
            break;

        case 19:
            printf(" and your age is 19\n so you will get 75 percent off in your admission fees as scholarship\n");
            break;

        case 20:
            printf(" and your age is 20\n so you will get 65 percent off in your admission fees as scholarship\n");
            break;

        default:
            printf("As your age is either below 18 or above 20 you will not get any scholarship\n but dont be afraid your future is full of bright colour\n");
            break;
        }
        break;
    case 95:
        printf("You have got 95 percent in your class 12th examination\n");
        switch (age)
        {
        case 18:
            printf(" and your age is 18\n so you will get 90 percent off in your admission fees as scholarship\n");
            break;

        case 19:
            printf(" and your age is 19\n so you will get 80 percent off in your admission fees as scholarship\n");
            break;

        case 20:
            printf(" and your age is 20\n so you will get 70 percent off in your admission fees as scholarship\n");
            break;

        default:
            printf("As your age is either below 18 or above 20 you will not get any scholarship\n Be strong you are future of our nation......\n");
            break;
        }
        break;
    case 100:
        printf("Glad to hear that\n You have got 100 percent in your class 12th examination\n");
        switch (age)
        {
        case 18:
            printf(" and your age is 18\n so you are not required to pay any admission fees\n cheers!!!\n");
            break;

        case 19:
            printf(" and your age is 19 \nso you have to pay just 5 percent of your admission fees\n");
            break;

        case 20:
            printf("and your age is 20\n so you have to pay just 10 percent of your admission fees\n");
            break;

        default:
            printf("As your age is either below 18 or above 20 you will not get any scholarship\n but are and will be flying high in the sky\n");
            break;
        }
        break;

    default:
        printf("Either your age is below 18 or above 20\n or you havent got that good marks in your class 12th examination\n sorry to say but you are not eligible for any scholarship\n GOOD LUCK\n");
        break;
    }
    printf("HAVE A GREAT FUTURE AHEAD");
    return 0;
}
